server:
  port: 8000
spring:
  application:
    name: workflow-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hack3
    username: root
    password: 1234554321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      assignEditorToArticle:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 3
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
